language: node_js
node_js:
  - "6"
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - CXX=g++-4.8 TEST_SUITE=test:node
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "6"
      env: CXX=g++-4.8 TEST_SUITE=coveralls
    - os: linux
      node_js: "6"
      env: CXX=g++-4.8 TEST_SUITE=lint
script: npm run $TEST_SUITE
