language: node_js
node_js:
  - "7"
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - CXX=g++-4.8 TEST_SUITE=test
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "7"
      env: CXX=g++-4.8 TEST_SUITE=coveralls
    - os: linux
      node_js: "7"
      env: CXX=g++-4.8 TEST_SUITE=lint
script: npm run $TEST_SUITE
